version: '3.8'

services:
  jjcrawler:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: jjcrawler
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ../data:/app/data
    environment:
      - DEBUG=false
      - DATABASE_URL=sqlite:///./data/jjcrawler.db
      - CORS_ORIGINS=*
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s